---
apiVersion: v1
kind: Service
metadata:
  annotations:
    app.quarkus.io/build-timestamp: 2021-10-21 - 10:00:28 +0000
  labels:
    app.kubernetes.io/name: camunda-k8s-example
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  name: camunda-k8s-example
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
  selector:
    app.kubernetes.io/name: camunda-k8s-example
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.quarkus.io/build-timestamp: 2021-10-21 - 10:00:28 +0000
  labels:
    app.kubernetes.io/name: camunda-k8s-example
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  name: camunda-k8s-example
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: camunda-k8s-example
      app.kubernetes.io/version: 1.0.0-SNAPSHOT
  template:
    metadata:
      annotations:
        app.quarkus.io/build-timestamp: 2021-10-21 - 10:00:28 +0000
      labels:
        app.kubernetes.io/name: camunda-k8s-example
        app.kubernetes.io/version: 1.0.0-SNAPSHOT
    spec:
      containers:
        - env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          image: tasso/camunda-k8s-example:1.0.0-SNAPSHOT
          imagePullPolicy: IfNotPresent
          name: camunda-k8s-example
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: postgres
  name: postgres
spec:
  ports:
    - port: 5432
  selector:
    app: postgres
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: process-engine
            - name: POSTGRES_USER
              value: camunda
            - name: POSTGRES_PASSWORD
              value: camunda